server.port=8081
spring.application.name=work-load-service


spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

aws.region=us-east-1
aws.dynamodb.endpoint=https://dynamodb.us-east-1.amazonaws.com

cloud.aws.region.static=us-east-1
cloud.aws.sqs.queue.url=https://sqs.us-east-1.amazonaws.com/180294205143/Gym-Queue