spring.application.name=gym-app
# Logging
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm=DEBUG

# Server
server.port=8080


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.current_session_context_class=org.hibernate.context.internal.ThreadLocalSessionContext


spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=jdbc:postgresql://gym-db-instance.cv4mo6aako1x.us-east-1.rds.amazonaws.com:5432/projectdb
spring.datasource.username=postgres
spring.datasource.password=8621398a
spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:/sql/schema.sql
spring.sql.init.data-locations=classpath:/sql/data.sql  


cloud.aws.region.static=us-east-1
cloud.aws.sqs.queue.url=https://sqs.us-east-1.amazonaws.com/180294205143/Gym-Queue





